author: artur9010
name: SetSpawn
main: pl.artur9010.setspawn.SetSpawnPlugin
version: 2.3
website: http://artur9010.pl/
database: false


commands:
  spawn:
    description: Teleport to spawn
    permission: setspawn.spawn
    aliases: [sapwn, s]
    usage: spawn
  setspawn:
    description: Set spawn
    permission: setspawn.setspawn
    usage: setspawn
  rspawn:
      description: Reload SetSpawn
      permission: setspawn.rspawn
      usage: rspawn

permissions:
  setspawn.*:
    description: Access all setspawn commands
    children:
      setspawn.setspawn: true
      setspawn.spawn: true
      setspawn.rspawn: true
  setspawn.setspawn:
    description: Setspawn
    default: op
  setspawn.spawn:
    description: Teleport to spawn
    default: true
  setspawn.rspawn:
    description: Reload setspawn
    default: op